### ISSUE TITLE
Issue when npm run dev

### ISSUE THREAD

**Issue by cimptechhk** [w3bdesign/nextjs-woocommerce#1101]
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'dev'
1 verbose cli ]
2 info using npm@6.14.13
3 info using node@v14.17.0
4 verbose run-script [ 'predev', 'dev', 'postdev' ]
5 info lifecycle nextjs-woocommerce@1.1.7~predev: nextjs-woocommerce@1.1.7
6 info lifecycle nextjs-woocommerce@1.1.7~dev: nextjs-woocommerce@1.1.7
7 verbose lifecycle nextjs-woocommerce@1.1.7~dev: unsafe-perm in lifecycle true
8 verbose lifecycle nextjs-woocommerce@1.1.7~dev: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\felix\Downloads\nextjs-woocommerce-master\node_modules\.bin;C:\Program Files\Common Files\Oracle\Java\javapath;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Users\felix\AppData\Roaming\npm;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2\libnvvp;C:\Program Files (x86)\Common Files\Intel\Shared Libraries\redist\ia32\compiler;C:\Program Files (x86)\Common Files\Intel\Shared Libraries\redist\intel64\compiler;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files (x86)\QuickTime\QTSystem\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\NVIDIA Corporation\Nsight Compute 2019.5.0\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\;C:\Program Files\PuTTY\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Apache24\bin;C:\Program Files\dotnet\;C:\xampp\php;C:\composer;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\nodejs\;C:\Program Files (x86)\Bitvise SSH Client;C:\Program Files\Git\cmd;C:\Users\felix\AppData\Local\Programs\Python\Python38-32\Scripts\;C:\Users\felix\AppData\Local\Programs\Python\Python38-32\;C:\Program Files\MySQL\MySQL Shell 8.0\bin\;C:\Users\felix\AppData\Local\Microsoft\WindowsApps;C:\Users\felix\AppData\Local\GitHubDesktop\bin;C:\Users\felix\AppData\Local\atom\bin;C:\Users\felix\.dotnet\tools;C:\Users\felix\AppData\Roaming\Composer\vendor\bin;C:\Users\felix\AppData\Local\Microsoft\WindowsApps;C:\Users\felix\AppData\Local\Programs\Microsoft VS Code\bin
9 verbose lifecycle nextjs-woocommerce@1.1.7~dev: CWD: C:\Users\felix\Downloads\nextjs-woocommerce-master
10 silly lifecycle nextjs-woocommerce@1.1.7~dev: Args: [ '/d /s /c', 'next dev' ]
11 silly lifecycle nextjs-woocommerce@1.1.7~dev: Returned: code: 1  signal: null
12 info lifecycle nextjs-woocommerce@1.1.7~dev: Failed to exec dev script
13 verbose stack Error: nextjs-woocommerce@1.1.7 dev: `next dev`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:376:20)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:376:20)
13 verbose stack     at maybeClose (internal/child_process.js:1055:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
14 verbose pkgid nextjs-woocommerce@1.1.7
15 verbose cwd C:\Users\felix\Downloads\nextjs-woocommerce-master
16 verbose Windows_NT 10.0.19045
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "dev"
18 verbose node v14.17.0
19 verbose npm  v6.14.13
20 error code ELIFECYCLE
21 error errno 1
22 error nextjs-woocommerce@1.1.7 dev: `next dev`
22 error Exit status 1
23 error Failed at the nextjs-woocommerce@1.1.7 dev script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by w3bdesign** [comment]
@cimptechhk 

Your Node and npm version is too old and is not supported.

You should ensure you are using the following versions to avoid any issues:

```
$ node --version
v18.16.1


$ npm --version
9.1.2
```
