### ISSUE TITLE
Graphql Error

### ISSUE THREAD

**Issue by sohaibMan** [w3bdesign/nextjs-woocommerce#1103]
ApolloError: Cannot query field "allPaColors" on type "VariableProduct".
Cannot query field "allPaSizes" on type "VariableProduct"

**Comment by w3bdesign** [comment]
@sohaibMan 

Read the troubleshooting section here: 

https://github.com/w3bdesign/nextjs-woocommerce#troubleshooting

You need the size and color attribute.
