### ISSUE TITLE
Token expiration

### ISSUE THREAD

**Issue by w3bdesign** [w3bdesign/nextjs-woocommerce#1149]
When we add a product to the cart, and visit the store a week later or so, we get a token expiration error.

The fix for this is to manually clear the local storage, which is not ideal.

**Comment by w3bdesign** [comment]
@adentranter

**Comment by adentranter** [comment]
@w3bdesign Thanks for tagging me. 

Are you deving this site for research purposes?
I want to use this to run a full site; However the first thing ive done is remove all your native language. 

Love to help push back any of my code back into this repo if you want it... 

So let me know. 
Thanks

**Comment by w3bdesign** [comment]
> @w3bdesign Thanks for tagging me.
> 
> Are you deving this site for research purposes? I want to use this to run a full site; However the first thing ive done is remove all your native language.
> 
> Love to help push back any of my code back into this repo if you want it...
> 
> So let me know. Thanks

@adentranter 

I sent you an email earlier today explaining the purpose of this repo. You should check your spam folder in case it ended up there.

I believe i18n routing would be a better option, as then the language can be more easily translated for international use, rather than having to hardcode text everwyhere. I believe this is documented in https://nextjs.org/docs/pages/building-your-application/routing/internationalization but I have not tested this myself yet. 

What changes have you made besides changing the text/translation?

**Comment by adentranter** [comment]
@w3bdesign thats the only change so far and that reads nicely. 

[TODO](https://github.com/w3bdesign/nextjs-woocommerce#todo)
from that list. 
    plan to handle
    -  Add better SEO
    -    Add total to cart/checkout page
    -     Copy billing address to shipping address
    -     Hide products not in stock
    -    Add order dashboard and require login ( this is for user users )
        - /orders & /order/:id shall go to where you can 
       
       bunch more but they will slowly come to me. 
       
       If im first working on basic items within the issues. Should i commit to my repo and then do a PR to you? for a specific #issue now. 
       
       anyway, I replied to your email :dagger:

**Comment by w3bdesign** [comment]
@adentranter 

Hope it is okay that I assigned this issue to you, as it is a bug that will also affect your store unless it is fixed.

I will check my email later today.

**Comment by w3bdesign** [comment]
@adentranter 

Any ETA on this?

**Comment by tan-ahmed** [comment]
@adentranter any ETA?

**Comment by w3bdesign** [comment]
> @adentranter any ETA?

@tan-ahmed 

I'll have to fix this personally if he doesn't get back to me very soon.

**Comment by adentranter** [comment]
I'll get onto this today. 
Give me a few hours and I'll have an update. 

I just have to go run an errand first.

**Comment by adentranter** [comment]
@w3bdesign dumb question.
Best way to test this is to setup a dummy woo db along with having ALGOLIA setup for it.

Also, How long do you want the cart to stay in the cart? IE how long before i clear the cart?

Cheers.

**Comment by w3bdesign** [comment]
> @w3bdesign dumb question. Best way to test this is to setup a dummy woo db along with having ALGOLIA setup for it.
> 
> Also, How long do you want the cart to stay in the cart? IE how long before i clear the cart?
> 
> Cheers.

@adentranter 

I think up to 1 week would probably be reasonable, any longer would likely be unnecessary.

But for a production ecommerce site, it could make sense to extend it to 30 days or so.

**Comment by adentranter** [comment]
@w3bdesign that sounds realistic. 

Two points I want to make as I've never really helped an open source project such as this one but I want to help more. 
- the fact that you need a random wordpress site setup with variable such as color/size - Just confuses and complicates the ability to work on it. 

If you could use your graphql it would be ok - but there is a heap of ALGOLIA cors isssues - which i get. 

But it just makes something such as this which is an easy to do task. But to test it, requires real data - I would use my dev version of my  woocommerce site - but I tried for an hour to add the attributes for size and color as they are required.
So then i get the error

```
Uncaught ApolloError: Cannot query field "allPaColors" on type "VariableProduct".
Cannot query field "allPaSizes" on type "VariableProduct"
```
The example product on the db looks like this https://imgur.com/a/Dvwcnuy

But still throwing errors.

**Comment by w3bdesign** [comment]
@adentranter 

Try to make sure attributes looks like this:

![image](https://github.com/w3bdesign/nextjs-woocommerce/assets/45217974/578b3410-f2f0-4eea-80a4-c1d20907fb80)

**Comment by tan-ahmed** [comment]
> @w3bdesign that sounds realistic.
> 
> Two points I want to make as I've never really helped an open source project such as this one but I want to help more.
> 
> * the fact that you need a random wordpress site setup with variable such as color/size - Just confuses and complicates the ability to work on it.
> 
> If you could use your graphql it would be ok - but there is a heap of ALGOLIA cors isssues - which i get.
> 
> But it just makes something such as this which is an easy to do task. But to test it, requires real data - I would use my dev version of my woocommerce site - but I tried for an hour to add the attributes for size and color as they are required. So then i get the error
> 
> ```
> Uncaught ApolloError: Cannot query field "allPaColors" on type "VariableProduct".
> Cannot query field "allPaSizes" on type "VariableProduct"
> ```
> 
> The example product on the db looks like this https://imgur.com/a/Dvwcnuy
> 
> But still throwing errors.

I've had the same issue and so did my friend.

**Comment by w3bdesign** [comment]
@adentranter @tan-ahmed 

This has been solved and I am merging the fix into master.
