### ISSUE TITLE
Use CoCart to complete project

### ISSUE THREAD

**Issue by seb86** [w3bdesign/nextjs-woocommerce#159]
I think you will be able to complete this project with the help of my plugin [CoCart](https://cocart.xyz) specially with the session handling. Let me know if you have any questions.

**Comment by w3bdesign** [comment]
Thanks for the tip @seb86 , but I have done research into this, and I have no use for CoCart.

The cart is stored inside localstorage, and the actual checkout process is handled by Graphql, so implementing CoCart would just add an extra unnecessary layer. 

I recommend that you take a look at the code, and you will see how the cart and the checkout process is handled.

**Comment by seb86** [comment]
Very well.
