### ISSUE TITLE
Fix "similar-code" issue in components/Checkout/Billing.component.jsx

### ISSUE THREAD

**Issue by w3bdesign** [w3bdesign/nextjs-woocommerce#618]
Similar blocks of code found in 2 locations. Consider refactoring.

https://codeclimate.com/github/w3bdesign/nextjs-woocommerce/components/Checkout/Billing.component.jsx#issue_615d155cdf9ab70001000070

**Comment by zaxoavoki** [comment]
Hello. I would like to take care of refactoring. Could you assign the issue to me?
