### ISSUE TITLE
[Codefactor] Missing dependencies in useEffect

### ISSUE THREAD

**Issue by w3bdesign** [w3bdesign/nextjs-woocommerce#852]
#### React Hook useEffect has a missing dependency: &#39;refetch&#39;. Either include it or remove the dependency array.
- [x]  [components\Cart\CartPage\CartItemsContainer.component.jsx:77](https://github.com/w3bdesign/nextjs-woocommerce/blob/ba10566f52270e51f333e614033bc1201f00ed2e/components/Cart/CartPage/CartItemsContainer.component.jsx#L77)
- [ ]  [components\Checkout\CheckoutForm.component.jsx:63](https://github.com/w3bdesign/nextjs-woocommerce/blob/ba10566f52270e51f333e614033bc1201f00ed2e/components/Checkout/CheckoutForm.component.jsx#L63)

#### React Hook useEffect has a missing dependency: &#39;product.variations&#39;. Either include it or remove the dependency array.
- [ ]  [components\Product\SingleProduct.component.jsx:25](https://github.com/w3bdesign/nextjs-woocommerce/blob/ba10566f52270e51f333e614033bc1201f00ed2e/components/Product/SingleProduct.component.jsx#L25)

#### passHref is missing. See: https://nextjs.org/docs/messages/link-passhref
- [ ]  [components\Cart\CartPage\CartItemsContainer.component.jsx:99](https://github.com/w3bdesign/nextjs-woocommerce/blob/ba10566f52270e51f333e614033bc1201f00ed2e/components/Cart/CartPage/CartItemsContainer.component.jsx#L99)
- [ ]  [components\AlgoliaSearch\SearchResults.component.jsx:33](https://github.com/w3bdesign/nextjs-woocommerce/blob/ba10566f52270e51f333e614033bc1201f00ed2e/components/AlgoliaSearch/SearchResults.component.jsx#L33)
- [ ]  [components\Category\Categories.component.jsx:15](https://github.com/w3bdesign/nextjs-woocommerce/blob/ba10566f52270e51f333e614033bc1201f00ed2e/components/Category/Categories.component.jsx#L15)

#### React Hook useEffect has a missing dependency: &#39;checkout&#39;. Either include it or remove the dependency array.
- [ ]  [components\Checkout\CheckoutForm.component.jsx:59](https://github.com/w3bdesign/nextjs-woocommerce/blob/ba10566f52270e51f333e614033bc1201f00ed2e/components/Checkout/CheckoutForm.component.jsx#L59)

**Comment by ninearif** [comment]
Can I ask why you need to refetch() repeatedly while it's already fetching data from grapql for you?

**Comment by w3bdesign** [comment]
> Can I ask why you need to refetch() repeatedly while it's already fetching data from grapql for you?
> 
> let's start with these lines of code in CartItemsContainer
> 
> https://github.com/w3bdesign/nextjs-woocommerce/blob/ba10566f52270e51f333e614033bc1201f00ed2e/components/Cart/CartPage/CartItemsContainer.component.jsx#L38-L40
> 
> https://github.com/w3bdesign/nextjs-woocommerce/blob/ba10566f52270e51f333e614033bc1201f00ed2e/components/Cart/CartPage/CartItemsContainer.component.jsx#L75-L77

@ninearif 
I needed to use refetch to fix a bug with items not being added to the cart

**Comment by ninearif** [comment]
> > Can I ask why you need to refetch() repeatedly while it's already fetching data from grapql for you?
> > let's start with these lines of code in CartItemsContainer
> > https://github.com/w3bdesign/nextjs-woocommerce/blob/ba10566f52270e51f333e614033bc1201f00ed2e/components/Cart/CartPage/CartItemsContainer.component.jsx#L38-L40
> > 
> > https://github.com/w3bdesign/nextjs-woocommerce/blob/ba10566f52270e51f333e614033bc1201f00ed2e/components/Cart/CartPage/CartItemsContainer.component.jsx#L75-L77
> 
> @ninearif I needed to use refetch to fix a bug with items not being added to the cart

I think this is not how we deal with that issue, can you give some examples or explanations on how I can reproduce that bug?

**Comment by w3bdesign** [comment]
Remove refetch() and try
