### ISSUE TITLE
Padding for input field can be added for better UI experience

### ISSUE THREAD

**Issue by bikkimahato** [w3bdesign/nextjs-woocommerce#871]
**Describe the bug**
Padding for input field can be added for better UI experience.

**Screenshots**
![image](https://user-images.githubusercontent.com/42492682/176719532-d095999e-7f99-4b6d-baa2-fac236e27327.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: chrome
 - Version 103.0.5060.66

**Comment by w3bdesign** [comment]
@bikkimahato 

Actually this icon is not needed, so I have hidden it with CSS.
